"""
Critic Agent — evaluates the investment plan for quality, accuracy, and regulatory
compliance. Adds SEBI/AMFI disclaimers. Can trigger a retry if quality is poor.
"""
from loguru import logger
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage

from src.graph.state import FinanceAdvisorState, AgentMessage
from src.utils.config import config


SEBI_DISCLAIMER = """
---
**REGULATORY DISCLAIMER**

*This investment advice is generated by an AI system and is for educational and informational purposes only. It does not constitute professional financial advice, a solicitation, or a recommendation to buy or sell any securities.*

- **SEBI Registration**: This system is not registered with SEBI as an Investment Adviser under IA Regulations, 2013.
- **Mutual Fund Investments**: Mutual fund investments are subject to market risks. Please read all scheme related documents carefully before investing.
- **Past Performance**: Past performance is not indicative of future results.
- **Tax Advice**: Tax computations are indicative. Consult a qualified CA/tax advisor for your specific situation.
- **Personalization**: This advice is based on information provided by you and may not account for all financial circumstances.

*Please consult a SEBI-registered investment adviser before making significant financial decisions.*
*AMFI Registration No. of funds mentioned can be verified at www.amfiindia.com*
"""

CRITIC_SYSTEM_PROMPT = """You are a critical evaluator and compliance officer reviewing AI-generated financial advice for Indian users.

Your evaluation criteria:

## 1. Factual Accuracy (0-10)
- Are market figures realistic and internally consistent?
- Are tax slabs and deduction limits correct for FY 2024-25?
- Are return assumptions reasonable (equity 10-15%, debt 6-8%)?
- Are product names and their properties accurate?

## 2. Hallucination Check (0-10)
- Does the plan reference specific data that wasn't in the context?
- Are fund names real Indian mutual funds?
- Are regulatory limits correctly stated (80C: ₹1.5L, 80CCD: ₹50K, 80D: ₹25K)?

## 3. Personalization (0-10)
- Is the advice tailored to the user's income, age, and risk appetite?
- Are recommendations proportionate to income?

## 4. Actionability (0-10)
- Are steps specific and implementable?
- Are timelines and amounts clear?

## 5. Completeness (0-10)
- Does the plan cover: emergency fund, insurance, tax optimization, long-term investment?
- Are risks mentioned?

## Output Format:
Provide:
1. Scores for each criterion
2. Overall score (average)
3. List of issues found (if any)
4. IMPROVED VERSION of the plan with corrections applied
5. Decision: APPROVE or RETRY (retry if overall score < 6)

If you APPROVE, output the final polished plan.
If you RETRY, output specific instructions for the Planner to improve.
"""


def run_critic(state: FinanceAdvisorState) -> FinanceAdvisorState:
    """Execute the Critic agent node in the LangGraph workflow."""
    logger.info("Critic agent started")
    state["current_agent"] = "critic"

    try:
        llm = ChatGroq(
            api_key=config.GROQ_API_KEY,
            model=config.LLM_MODEL,
            temperature=0.1,
        )

        plan = state.get("plan_output", "No plan generated.")
        query = state["user_query"]
        analysis = state.get("analysis_output", "")
        research = state.get("research_output", "")
        profile = state.get("user_profile", {})
        iteration = state.get("iteration", 0)

        messages = [
            SystemMessage(content=CRITIC_SYSTEM_PROMPT),
            HumanMessage(
                content=f"""Evaluate this investment plan:

USER QUERY: {query}
USER PROFILE: Age={profile.get('age', 'N/A')}, Income=₹{profile.get('income', 'N/A')}, Risk={profile.get('risk_appetite', 'moderate')}

=== PLAN TO EVALUATE ===
{plan}

=== CONTEXT USED ===
Analysis: {analysis[:500] if analysis else 'None'}
Research: {research[:500] if research else 'None'}

Iteration: {iteration + 1} of 2 (after 2 iterations, always APPROVE)
{"NOTE: This is the final iteration. You MUST APPROVE regardless of quality." if iteration >= 1 else ""}

Provide your evaluation and the final improved plan."""
            ),
        ]

        response = llm.invoke(messages)
        critic_output = response.content

        # Parse decision from response
        should_retry = (
            "RETRY" in critic_output.upper()
            and iteration < 1  # Max 1 retry
        )

        # Build final structured output
        final_plan = _extract_final_plan(critic_output, plan)
        summary = _generate_summary(final_plan, llm, query)

        state["critic_output"] = critic_output
        state["should_retry"] = should_retry
        state["iteration"] = iteration + 1

        if not should_retry:
            state["final_advice"] = final_plan
            state["summary"] = summary
            state["disclaimer"] = SEBI_DISCLAIMER

        state["messages"].append(
            AgentMessage(
                agent="critic",
                content=critic_output,
                tool_calls=None,
                metadata={
                    "should_retry": should_retry,
                    "iteration": iteration + 1,
                },
            )
        )
        logger.success(f"Critic completed: retry={should_retry}, iteration={iteration+1}")

    except Exception as e:
        logger.error(f"Critic agent failed: {e}")
        state["critic_output"] = f"Evaluation failed: {e}"
        state["final_advice"] = state.get("plan_output", "Plan unavailable.")
        state["disclaimer"] = SEBI_DISCLAIMER
        state["should_retry"] = False
        state["error"] = str(e)

    return state


def _extract_final_plan(critic_output: str, original_plan: str) -> str:
    """Extract the improved plan from critic output, fallback to original."""
    # Look for sections indicating the improved plan
    markers = [
        "IMPROVED VERSION",
        "FINAL PLAN",
        "APPROVED PLAN",
        "CORRECTED PLAN",
        "## Final Investment Plan",
        "### Final Investment Plan",
    ]
    for marker in markers:
        if marker.lower() in critic_output.lower():
            idx = critic_output.lower().find(marker.lower())
            return critic_output[idx:].strip()

    # If critic just approved without major changes, return original
    if "APPROVE" in critic_output.upper():
        return original_plan

    return critic_output


def _generate_summary(plan: str, llm, query: str) -> str:
    """Generate a concise one-paragraph summary of the investment plan."""
    try:
        response = llm.invoke([
            HumanMessage(
                content=f"""Summarize this investment plan in exactly 3-4 sentences for a busy Indian professional.
Focus on: total investment recommended, expected returns, and top 2-3 actionable steps.

Plan: {plan[:2000]}

Write the summary in simple, jargon-free language."""
            )
        ])
        return response.content
    except Exception:
        return plan[:500] + "..."
